name: Playwright (positive only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install   # <<< заменили npm ci на npm install

      - name: Install Playwright (Chromium only)
        run: npx playwright install --with-deps chromium

      - name: Run positive tests (Chromium)
        run: npx playwright test positive/ --project=chromium

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
